steps:
- name: "python:3.10"
  entrypoint: python
  args: ["config.py"]
  env:
    - 'CLIENT_SECRET=${_CLIENT_SECRET}'
    
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"